version: "3"

services:
  inventory_db:
    container_name: inventory_db
    image: postgres:16.1-alpine
    env_file:
      - ./postgres/.env

  inventory_be: &base_app
    container_name: inventory_be
    build:
      context: ../
      dockerfile: ./docker/inventory/Dockerfile.local
    command: python inventory/manage.py runserver 0.0.0.0:8000
    volumes:
      - ../:/app
    env_file:
      - ./inventory/.env.local
    depends_on:
      - inventory_db
    ports:
      - 8000:8000
